pipeline {
	agent any
	stages {
		stage('Git-checkout') {
			steps {
					git credentialsId: '9fd82d11-bcd3-4c2c-8cf0-0d9248a8f345', url: 'https://github.com/vivekragi/sample-spring-microservices.git'
			}
		}
		stage('Build') {
			steps {
				bat label: '', script: 'mvn --version'
			}
		}
		stage('test') {
			steps {
				echo "Successfully ran test cases"
			}
		}
	}
}
